Upload page redesigned and re implemented
Prajith007007/Fodgers_DHT pull request #41
Opened 2021-06-23 14:38 UTC by tewarig

This pr solves #33 
as discuss this pr adds

 sidebar for navigation (animated)
 separate upload button
 own image gallery (responsive)
 click to zoom feature (single click to zoom in and zoom out)
 newly updated image gallery and upload functionality.
also, this fixes issue which was found in  #39 
![Images](https://user-images.githubusercontent.com/54894783/123116523-9bc00880-d45e-11eb-858b-388453c9e192.jpg)

2021-06-24 15:09 UTC, pkesavap commented
Once the user has logged in, it should reroute to the upload page where the user can upload a photo.
Right now, its being reloaded to /

@tewarig

2021-06-24 15:25 UTC, pkesavap requested changes
Add reroute for upload after user logs in

2021-06-24 16:21 UTC, tewarig reviewed
hi,  @pkesavap  check this he is being redirected to the upload route

2021-06-24 16:21 UTC, tewarig commented on app.py
>                  return render_template("login.html")
hi, it is already there if user login, he would be redirected to the upload route.

2021-06-24 16:25 UTC, tewarig commented
<iframe width="560" height="315" src="https://www.youtube.com/embed/Ly8aE130b14" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen={true}></iframe> 
here is a preview of that

2021-06-28 18:32 UTC, pkesavap commented
Ah my bad cookie problem. ;)

LGTM

2021-06-28 18:32 UTC, merged